title: AI reference
author: Thijs van den Hout
email: thijsvandenhout@live.nl
description: Page with useful links and references for the AI bachelor at Radboud University
twitter_username: thijsvandenhout
github_username: tvdhout

theme: minima
