title: AI reference
author: Thijs van den Hout
email: thijsvandenhout@live.nl
description: Page with useful links and other resources for the AI bachelor at Radboud University
twitter_username: thijsvandenhout
github_username: tvdhout

theme: minima

header_pages:
  - Tools.md
  - Tips.md
  - Programming.md
  - Courses.md
  - Campus.md
  - Nijmegen.md
